import Link from "next/link";
import { ArrowRight, Check, ChevronDown, Sparkles } from "lucide-react";
import { createClient } from "@/lib/supabase/server";

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const {slug}=await params; const supabase=await createClient(); const {data}=await supabase.from("services").select("name,short_description").eq("slug",slug).eq("is_active",true).maybeSingle(); return {title:data?.name ?? "Service",description:data?.short_description ?? "ARSHI GROUP service"}; }
export default async function ServiceDetail({ params }: { params: Promise<{ slug: string }> }) {
  const {slug}=await params; const supabase=await createClient(); const {data:s}=await supabase.from("services").select("*").eq("slug",slug).eq("is_active",true).maybeSingle();
  if(!s) return <main className="section-wrap"><h1 className="text-4xl font-black">Service not found</h1><Link href="/services" className="mt-6 inline-block text-blue-600">← All services</Link></main>;
  const features=Array.isArray(s.features)?s.features:[]; const pricing=Array.isArray(s.pricing)?s.pricing:[]; const faqs=Array.isArray(s.faqs)?s.faqs:[];
  return <main><section className="section-wrap"><Link href="/services" className="text-sm font-bold text-muted-foreground">← All services</Link><div className="mt-12 max-w-4xl"><div className="inline-flex items-center gap-2 rounded-full border border-blue-500/20 bg-blue-500/10 px-4 py-2 text-xs font-bold uppercase tracking-[.18em] text-blue-600 dark:text-blue-300"><Sparkles className="size-4"/> ARSHI GROUP</div><h1 className="mt-6 text-5xl font-black tracking-tight sm:text-7xl">{s.hero_title || s.name}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">{s.hero_description || s.description}</p><Link href="/contact" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-6 py-3.5 font-bold text-white">{s.cta_label || "Start a project"}<ArrowRight className="size-4"/></Link></div></section><section className="mx-auto max-w-7xl px-5 pb-24"><div className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border border-border bg-card p-7"><p className="text-sm font-bold uppercase tracking-widest text-muted-foreground">What you get</p><div className="mt-6 space-y-4">{features.map((f:string)=><div key={f} className="flex gap-3"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-blue-500/10"><Check className="size-4 text-blue-500"/></span><span>{f}</span></div>)}</div></div><div className="rounded-3xl border border-border bg-card p-7"><p className="text-sm font-bold uppercase tracking-widest text-muted-foreground">Packages</p><div className="mt-6 space-y-3">{pricing.map((p:{name?:string;description?:string;price?:string})=><div key={p.name} className="flex items-center justify-between gap-4 rounded-2xl border border-border p-4"><div><p className="font-bold">{p.name}</p><p className="mt-1 text-sm text-muted-foreground">{p.description}</p></div><span className="shrink-0 text-sm font-black">{p.price}</span></div>)}</div></div></div><div className="mt-8 rounded-3xl border border-border bg-card p-7"><p className="text-sm font-bold uppercase tracking-widest text-muted-foreground">FAQs</p><div className="mt-5 divide-y divide-border">{faqs.map((f:{q?:string;a?:string})=><details key={f.q} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-bold">{f.q}<ChevronDown className="size-4 transition group-open:rotate-180"/></summary><p className="mt-3 max-w-3xl leading-7 text-muted-foreground">{f.a}</p></details>)}</div></div></section></main>;
}
