'use client';

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, Image as ImageIcon, KeyRound, Mail, Save, ShieldCheck, UserRound } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

const defaults = {
  light: "/brand/arshi-light.svg",
  dark: "/brand/arshi-dark.svg",
  icon: "/brand/arshi-icon.svg",
};

function validAsset(value: string) {
  return value.startsWith("/") || value.startsWith("https://");
}

export default function AdminSettingsPage() {
  const [name,setName]=useState(""); const [email,setEmail]=useState("");
  const [newPassword,setNewPassword]=useState(""); const [confirmPassword,setConfirmPassword]=useState("");
  const [light,setLight]=useState(defaults.light); const [dark,setDark]=useState(defaults.dark); const [icon,setIcon]=useState(defaults.icon);
  const [status,setStatus]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);

  useEffect(()=>{(async()=>{try{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user) return;setEmail(user.email||"");const {data:p}=await s.from("profiles").select("full_name").eq("id",user.id).maybeSingle();setName(p?.full_name||"");const {data:settings}=await s.from("site_settings").select("light_logo_url,dark_logo_url,icon_logo_url").eq("id",true).maybeSingle();if(settings){setLight(settings.light_logo_url||defaults.light);setDark(settings.dark_logo_url||defaults.dark);setIcon(settings.icon_logo_url||defaults.icon)}}catch(e){setError(e instanceof Error?e.message:"Unable to load settings.")}finally{setLoading(false)}})()},[]);

  async function saveAccount(e:FormEvent){e.preventDefault();setError("");setStatus("");setSaving(true);try{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user) throw new Error("Your admin session has expired. Please sign in again.");const {error:profileError}=await s.from("profiles").update({full_name:name.trim().slice(0,100)}).eq("id",user.id);if(profileError) throw profileError;if(email.trim().toLowerCase()!==user.email?.toLowerCase()){const {error:emailError}=await s.auth.updateUser({email:email.trim().toLowerCase()});if(emailError) throw emailError;}
    if(newPassword){if(newPassword.length<8) throw new Error("Password must be at least 8 characters.");if(newPassword!==confirmPassword) throw new Error("New passwords do not match.");const {error:passwordError}=await s.auth.updateUser({password:newPassword});if(passwordError) throw passwordError;setNewPassword("");setConfirmPassword("");}
    setStatus("Admin account updated successfully.");
  }catch(e){setError(e instanceof Error?e.message:"Unable to update the admin account.")}finally{setSaving(false)}}

  async function saveLogos(e:FormEvent){e.preventDefault();setError("");setStatus("");if(![light,dark,icon].every(validAsset)){setError("Logo URLs must use a local /path or HTTPS URL.");return}setSaving(true);try{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user) throw new Error("Your admin session has expired.");const {error:e}=await s.from("site_settings").upsert({id:true,light_logo_url:light.trim().slice(0,1000),dark_logo_url:dark.trim().slice(0,1000),icon_logo_url:icon.trim().slice(0,1000),updated_by:user.id},{onConflict:"id"});if(e) throw e;setStatus("Logo settings saved. Refresh the website to see the new branding.")}catch(e){setError(e instanceof Error?e.message:"Unable to save logo settings. Run the site_settings SQL setup first if this is a new database.")}finally{setSaving(false)}}

  if(loading) return <main className="min-h-screen bg-[#050816] p-6 text-white"><div className="mx-auto max-w-5xl animate-pulse rounded-3xl border border-white/10 bg-white/[.03] p-10">Loading admin settings…</div></main>;
  return <main className="min-h-screen bg-[#050816] p-4 text-white sm:p-8"><div className="mx-auto max-w-5xl">
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.25em] text-blue-400">Administration</p><h1 className="mt-2 text-3xl font-black">Control Center Settings</h1><p className="mt-2 text-sm text-slate-400">Manage the admin identity and ARSHI GROUP branding.</p></div><Link href="/admin" className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-sm font-bold text-slate-300 hover:bg-white/5"><ArrowLeft className="h-4 w-4"/> Admin dashboard</Link></div>
    {error&&<div role="alert" className="mb-5 rounded-2xl border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-300">{error}</div>}{status&&<div role="status" className="mb-5 flex items-center gap-2 rounded-2xl border border-emerald-500/20 bg-emerald-500/10 p-4 text-sm text-emerald-300"><CheckCircle2 className="h-4 w-4"/>{status}</div>}
    <section className="grid gap-5 lg:grid-cols-2"><form onSubmit={saveAccount} className="rounded-3xl border border-white/10 bg-white/[.035] p-6 shadow-2xl"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-500/10 text-blue-300"><UserRound className="h-5 w-5"/></div><div><h2 className="font-black">Admin account</h2><p className="text-xs text-slate-500">Your login identity and security</p></div></div><label className="mt-6 block text-xs font-bold text-slate-400">Admin username / display name<input value={name} onChange={e=>setName(e.target.value)} maxLength={100} required className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-blue-500"/></label><label className="mt-4 block text-xs font-bold text-slate-400">Admin login email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" maxLength={254} required className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-blue-500"/></label><div className="mt-5 rounded-2xl border border-blue-400/10 bg-blue-400/5 p-4 text-xs leading-5 text-slate-400"><Mail className="mb-2 h-4 w-4 text-blue-300"/>Changing the email may require confirmation by Supabase before the new address becomes active.</div><label className="mt-5 block text-xs font-bold text-slate-400">New password<input value={newPassword} onChange={e=>setNewPassword(e.target.value)} type="password" minLength={8} autoComplete="new-password" placeholder="Leave blank to keep current password" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-blue-500"/></label><label className="mt-4 block text-xs font-bold text-slate-400">Confirm new password<input value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} type="password" minLength={8} autoComplete="new-password" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-blue-500"/></label><button disabled={saving} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-black disabled:opacity-60"><KeyRound className="h-4 w-4"/>{saving?"Saving…":"Save account"}</button></form>
    <form onSubmit={saveLogos} className="rounded-3xl border border-white/10 bg-white/[.035] p-6 shadow-2xl"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-500/10 text-blue-300"><ImageIcon className="h-5 w-5"/></div><div><h2 className="font-black">Logo manager</h2><p className="text-xs text-slate-500">Change light, dark and favicon assets</p></div></div>{[["Light logo",light,setLight],["Dark logo",dark,setDark],["Icon / favicon",icon,setIcon]].map(([label,value,setter])=><label key={label as string} className="mt-5 block text-xs font-bold text-slate-400">{label as string}<input value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)} maxLength={1000} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm outline-none focus:border-blue-500"/></label>)}<div className="mt-5 grid grid-cols-3 gap-3 rounded-2xl border border-white/10 bg-black/20 p-4"><div className="rounded-xl bg-white p-3"><img src={light} alt="Light logo preview" className="h-12 w-full object-contain"/></div><div className="rounded-xl bg-black p-3"><img src={dark} alt="Dark logo preview" className="h-12 w-full object-contain"/></div><div className="grid place-items-center rounded-xl bg-white p-3"><img src={icon} alt="Icon preview" className="h-12 w-12 object-contain"/></div></div><button disabled={saving} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-black disabled:opacity-60"><Save className="h-4 w-4"/>{saving?"Saving…":"Save logos"}</button><p className="mt-4 flex gap-2 text-xs leading-5 text-slate-500"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-blue-400"/>Only staff roles can change these settings. Never paste secret keys into this page.</p></form></section>
  </div></main>;
}
