import Link from "next/link";
import { ArrowRight, Check, ExternalLink, ShieldCheck, WalletCards } from "lucide-react";

export const metadata = { title: "TikTok Ads Services", description: "ARSHI GROUP TikTok Ads account services, local top-up support and campaign assistance." };
const features=["TikTok Ads account support","Campaign setup and optimization","Creative and audience strategy","Local payment/top-up assistance","Tracking and performance reporting"];
const faqs=[
  ["Are you an official TikTok partner?","No. ARSHI GROUP is an independent service provider. We do not claim an official partnership with TikTok."],
  ["Can I access the advertising platform?","Yes. Use our Access Platform button to open the ARSHI GROUP TikTok Ads platform."],
  ["Do you provide local top-up support?","We can assist with available local payment/top-up workflows. Availability, limits and eligibility can vary."],
  ["Do you guarantee ad results?","No. Results depend on budget, offer, creative, audience, market and platform conditions."],
];
export default function TikTokAdsPage(){return <main><section className="section-wrap"><div className="grid gap-12 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><div className="inline-flex items-center gap-2 rounded-full border border-border bg-accent px-4 py-2 text-xs font-bold uppercase tracking-[.18em]"><ShieldCheck className="size-4 text-blue-500"/> Independent service provider</div><h1 className="mt-6 text-5xl font-black tracking-tight sm:text-7xl">Turn TikTok attention into a <span className="gradient-text">growth system.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">Account support, campaign execution and local top-up assistance from ARSHI GROUP — with direct access to our dedicated advertising platform.</p><div className="mt-8 flex flex-wrap gap-3"><a href="https://arshi-group.ecomdy.app/" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-6 py-3.5 font-bold text-white">Access Platform <ExternalLink className="size-4"/></a><Link href="/contact" className="inline-flex items-center gap-2 rounded-xl border border-border px-6 py-3.5 font-bold">Talk to our team <ArrowRight className="size-4"/></Link></div></div><div className="tiktok-card"><div className="flex items-center justify-between"><span className="text-sm font-bold">TikTok Ads workflow</span><WalletCards className="size-5 text-cyan-300"/></div><div className="mt-8 space-y-3">{features.slice(0,4).map((f,i)=><div key={f} className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/5 p-4"><span className="grid size-7 place-items-center rounded-full bg-white/10 text-xs font-black">0{i+1}</span><span className="text-sm font-semibold">{f}</span></div>)}</div></div></div></section><section className="mx-auto max-w-7xl px-5 pb-24"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{features.map(f=><div key={f} className="rounded-2xl border border-border bg-card p-5"><Check className="size-5 text-blue-500"/><p className="mt-4 text-sm font-bold leading-6">{f}</p></div>)}</div><div className="mt-10 rounded-3xl border border-border bg-card p-7"><h2 className="text-2xl font-black">TikTok Ads FAQs</h2><div className="mt-4 divide-y divide-border">{faqs.map(([q,a])=><details key={q} className="py-5"><summary className="cursor-pointer font-bold">{q}</summary><p className="mt-3 max-w-3xl leading-7 text-muted-foreground">{a}</p></details>)}</div></div></section></main>}
