import Link from "next/link";
import { ArrowRight, Bot, Check, ChevronDown, Code2, Globe2, Layers3, Megaphone, Search, ShieldCheck, ShoppingBag, Sparkles, Target, Workflow, Zap } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import ThemeToggle from "@/components/ThemeToggle";
import { Badge } from "@/components/ui/badge";
import { ButtonLink } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

type Service={title:string;text:string;icon:LucideIcon};
const services:Service[]=[
 {title:"Web & App Development",text:"High-performance websites and web applications engineered for speed, conversion and scale.",icon:Code2},
 {title:"E-commerce Systems",text:"Shopify, WooCommerce and custom commerce experiences built around your customer journey.",icon:ShoppingBag},
 {title:"Performance Marketing",text:"Meta, TikTok, Google, Snapchat and Pinterest acquisition systems driven by testing.",icon:Megaphone},
 {title:"SEO & Growth",text:"Technical SEO, content systems and conversion optimization that compound over time.",icon:Search},
 {title:"AI & Automation",text:"Intelligent workflows, AI assistants and business automations that remove repetitive work.",icon:Bot},
 {title:"Brand & Creative",text:"Distinct identities, campaigns and creative systems designed to earn attention.",icon:Sparkles},
];
const process=["Discover","Design","Build","Scale"];
const faqs=[["What does ARSHI GROUP do?","We combine digital strategy, web development, e-commerce, paid acquisition, SEO, AI automation and creative services under one team."],["Can you work with an existing website or store?","Yes. We can audit, redesign, rebuild, optimize or connect your existing systems."],["Do you manage TikTok Ads?","Yes. We offer TikTok Ads strategy, setup, campaign management, creative direction and optimization."],["How does a project start?","Send a project inquiry. We review your goals, current setup and priorities, then recommend the most practical next step."]];
function Heading({eyebrow,title,text}:{eyebrow:string;title:React.ReactNode;text?:string}){return <div className="max-w-3xl"><Badge>{eyebrow}</Badge><h2 className="mt-5 text-4xl font-black tracking-tight sm:text-6xl">{title}</h2>{text&&<p className="mt-5 text-base leading-8 text-muted-foreground sm:text-lg">{text}</p>}</div>}
export default function HomePage(){return <main className="min-h-screen overflow-hidden bg-background text-foreground">
<header className="sticky top-0 z-50 border-b border-border/70 bg-background/80 backdrop-blur-2xl"><nav className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/" className="text-2xl font-black tracking-tight">ARSHI<span className="text-blue-500">.</span>GROUP</Link><div className="hidden items-center gap-7 md:flex"><Link href="#services" className="nav-link">Services</Link><Link href="#work" className="nav-link">Work</Link><Link href="#process" className="nav-link">Process</Link><Link href="#faq" className="nav-link">FAQ</Link><ThemeToggle/><ButtonLink href="/contact" size="sm">Start a Project <ArrowRight size={15}/></ButtonLink></div><div className="flex items-center gap-2 md:hidden"><ThemeToggle/><details className="relative"><summary className="grid h-10 w-10 cursor-pointer list-none place-items-center rounded-full border border-border">☰</summary><div className="absolute right-0 top-12 w-52 rounded-2xl border border-border bg-card p-2 shadow-2xl"><Link className="mobile-nav" href="#services">Services</Link><Link className="mobile-nav" href="#work">Work</Link><Link className="mobile-nav" href="#process">Process</Link><Link className="mobile-nav" href="#faq">FAQ</Link><Link className="mobile-nav font-bold text-blue-500" href="/contact">Start a Project →</Link></div></details></div></nav></header>
<section className="hero-grid relative isolate"><div className="mx-auto grid min-h-[720px] max-w-7xl items-center gap-14 px-5 py-24 lg:grid-cols-[1.08fr_.92fr] lg:px-8"><div className="reveal"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-blue-500/20 bg-blue-500/10 px-4 py-2 text-xs font-bold uppercase tracking-[.18em] text-blue-500"><span className="pulse-dot"/> Digital growth partner</div><h1 className="text-5xl font-black leading-[.94] tracking-[-.06em] sm:text-7xl lg:text-[6.5rem]">Build bold.<br/><span className="gradient-text">Grow faster.</span></h1><p className="mt-8 max-w-2xl text-base leading-8 text-muted-foreground sm:text-xl">ARSHI GROUP creates high-performance websites, commerce systems, acquisition engines and AI-powered workflows for ambitious businesses.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><ButtonLink href="/contact" size="lg">Start a Project <ArrowRight size={18}/></ButtonLink><ButtonLink href="#work" variant="secondary" size="lg">Explore our work</ButtonLink></div><div className="mt-10 flex flex-wrap gap-5 text-xs font-bold uppercase tracking-widest text-muted-foreground"><span>Strategy-led</span><span>Conversion-focused</span><span>Built to scale</span></div></div><div className="relative reveal reveal-delay"><div className="orb orb-one"/><div className="orb orb-two"/><Card className="relative overflow-hidden p-6 sm:p-8"><div className="flex items-center justify-between border-b border-border pb-5"><div><p className="text-[10px] font-bold uppercase tracking-[.25em] text-blue-500">ARSHI / Growth OS</p><p className="mt-1 text-xl font-black">Digital systems</p></div><Zap className="text-blue-500"/></div><div className="mt-6 space-y-3">{["Strategy","Experience","Acquisition","Automation"].map((x,i)=><div key={x} className="flex items-center gap-4 rounded-2xl border border-border bg-background/60 p-4"><span className="grid size-9 place-items-center rounded-xl bg-blue-500/10 text-xs font-bold text-blue-500">0{i+1}</span><div><p className="text-sm font-bold">{x}</p><p className="text-xs text-muted-foreground">{["Positioning + roadmap","UX + high-performance build","Paid + organic growth","AI + connected workflows"][i]}</p></div><Check className="ml-auto text-emerald-500" size={17}/></div>)}</div><div className="mt-5 rounded-2xl border border-blue-500/15 bg-blue-500/5 p-5"><p className="text-[10px] font-bold uppercase tracking-widest text-blue-500">North star</p><p className="mt-2 text-2xl font-black">Better digital.<br/>Better growth.</p></div></Card></div></div></section>
<section className="border-y border-border bg-card/40"><div className="mx-auto grid max-w-7xl grid-cols-2 sm:grid-cols-3 lg:grid-cols-6">{services.map(s=><div key={s.title} className="flex items-center gap-3 border-border px-5 py-5 text-xs font-bold text-muted-foreground"><s.icon size={17} className="text-blue-500"/>{s.title}</div>)}</div></section>
<section id="services" className="section-wrap"><Heading eyebrow="Capabilities" title={<>One team. <span className="muted-gradient">Every digital layer.</span></>} text="Strategy, technology, commerce, performance marketing and automation connected into one growth system."/><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map((s,i)=><Card key={s.title} className="group p-7 transition duration-500 hover:-translate-y-2 hover:border-blue-500/30"><div className="flex justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-blue-500/10 text-blue-500"><s.icon size={23}/></span><span className="text-xs font-bold text-muted-foreground">0{i+1}</span></div><h3 className="mt-7 text-xl font-black">{s.title}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{s.text}</p><Link href="/services" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-blue-500">Explore capability <ArrowRight size={15}/></Link></Card>)}</div></section>
<section className="px-5 pb-24 lg:px-8"><div className="mx-auto max-w-7xl rounded-[2rem] border border-blue-500/20 bg-blue-500/5 p-8 sm:p-12 lg:p-16"><div className="grid gap-10 lg:grid-cols-[1fr_.7fr] lg:items-center"><div><Badge>TikTok Ads growth</Badge><h2 className="mt-5 text-4xl font-black sm:text-6xl">Turn attention into <span className="gradient-text">action.</span></h2><p className="mt-5 max-w-2xl leading-8 text-muted-foreground">Account support, campaign execution, creative testing, tracking and optimization through our dedicated TikTok Ads service.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{["Campaign strategy","Creative testing","Tracking setup","Performance optimization"].map(x=><div key={x} className="flex gap-3 text-sm font-semibold"><Check className="text-blue-500" size={17}/>{x}</div>)}</div><ButtonLink href="/services/tiktok-ads" className="mt-8">Explore TikTok Ads <ArrowRight size={16}/></ButtonLink></div><div className="tiktok-card"><Megaphone size={28}/><p className="mt-5 text-2xl font-black">TikTok Growth Engine</p><p className="mt-3 text-sm leading-6 text-white/60">Independent service provider. No official TikTok partnership is claimed.</p></div></div></div></section>
<section className="section-wrap pt-0"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><Heading eyebrow="Why ARSHI" title={<>Not just another <span className="muted-gradient">agency.</span></>} text="We think in systems, not isolated deliverables. Every decision should make the next decision easier, faster and more valuable."/><div className="grid gap-3 sm:grid-cols-2">{[[Globe2,"International mindset","Modern standards with practical execution."],[ShieldCheck,"Built with care","Performance, accessibility and security matter."],[Layers3,"Connected thinking","Design, development and growth stay aligned."],[Workflow,"Transparent process","Clear scope, communication and milestones."]].map(([Icon,title,text])=><Card key={String(title)} className="p-6"><Icon className="text-blue-500" size={22}/><h3 className="mt-5 font-black">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{String(text)}</p></Card>)}</div></div></section>
<section id="process" className="section-wrap border-y border-border bg-card/30"><Heading eyebrow="Process" title={<>Simple process. <span className="muted-gradient">Serious execution.</span></>}/><div className="mt-14 grid gap-4 md:grid-cols-4">{process.map((x,i)=><div key={x} className="border-l border-border pl-6"><span className="text-xs font-black text-blue-500">0{i+1}</span><h3 className="mt-4 text-xl font-black">{x}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{["Research, positioning and a clear roadmap.","UX, visual direction and conversion architecture.","Fast, reliable technology with clean foundations.","Launch, measure, optimize and keep improving."][i]}</p></div>)}</div></section>
<section id="work" className="section-wrap"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><Heading eyebrow="Selected work" title={<>Work that makes the <span className="muted-gradient">difference.</span></>}/><ButtonLink href="/portfolio" variant="secondary">View portfolio <ArrowRight size={16}/></ButtonLink></div><div className="mt-14 grid gap-5 lg:grid-cols-2">{["E-commerce Growth System","High-Performance Brand Platform","TikTok Acquisition Engine","AI Operations System"].map((x,i)=><Card key={x} className="overflow-hidden"><div className="case-visual"><Sparkles className="text-white"/><span className="ml-auto text-xs font-bold text-white/60">0{i+1}</span></div><div className="p-7"><p className="text-xs font-bold uppercase tracking-widest text-blue-500">Case study placeholder</p><h3 className="mt-3 text-2xl font-black">{x}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">Professional placeholder — replace with approved client results, visuals and verified metrics from the admin portfolio system.</p></div></Card>)}</div></section>
<section className="section-wrap border-y border-border bg-card/30"><Heading eyebrow="Testimonials" title={<>What clients will <span className="muted-gradient">say next.</span></>}/><div className="mt-12 grid gap-4 md:grid-cols-3">{["A polished placeholder for an approved client testimonial.","A future verified customer quote about strategy and execution.","A future verified customer quote about digital growth."] .map((q,i)=><Card key={i} className="p-7"><div className="flex gap-1 text-blue-500">{[1,2,3,4,5].map(n=><span key={n}>★</span>)}</div><p className="mt-5 leading-7">“{q}”</p><p className="mt-5 text-xs font-bold uppercase tracking-widest text-muted-foreground">Client name · Company</p></Card>)}</div></section>
<section id="faq" className="section-wrap"><Heading eyebrow="FAQ" title={<>Questions, answered <span className="muted-gradient">clearly.</span></>}/><div className="mt-10 max-w-4xl divide-y divide-border rounded-3xl border border-border bg-card px-6">{faqs.map(([q,a])=><details key={q} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 font-bold">{q}<ChevronDown className="size-5 transition group-open:rotate-180"/></summary><p className="mt-3 max-w-3xl leading-7 text-muted-foreground">{a}</p></details>)}</div></section>
<section className="px-5 pb-24 lg:px-8"><div className="mx-auto max-w-7xl rounded-[2rem] bg-foreground p-8 text-background sm:p-12 lg:p-16"><div className="flex flex-col justify-between gap-10 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.25em] opacity-60">Ready when you are</p><h2 className="mt-4 max-w-3xl text-4xl font-black sm:text-6xl">Let’s build something <span className="gradient-text">worth scaling.</span></h2><p className="mt-5 max-w-2xl leading-7 opacity-70">Tell us what you’re building, what’s blocking growth and where you want to go next.</p></div><ButtonLink href="/contact" variant="secondary" size="lg">Start a Project <ArrowRight size={18}/></ButtonLink></div></div></section>
<footer className="border-t border-border"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:grid-cols-2 lg:grid-cols-4 lg:px-8"><div className="sm:col-span-2"><Link href="/" className="text-2xl font-black">ARSHI<span className="text-blue-500">.</span>GROUP</Link><p className="mt-4 max-w-md text-sm leading-7 text-muted-foreground">Digital systems, growth and creative execution for ambitious businesses.</p></div><div><p className="footer-title">Explore</p><Link className="footer-link" href="/services">Services</Link><Link className="footer-link" href="/portfolio">Portfolio</Link><Link className="footer-link" href="/services/tiktok-ads">TikTok Ads</Link></div><div><p className="footer-title">Client</p><Link className="footer-link" href="/auth/login">Client login</Link><Link className="footer-link" href="/dashboard">Client portal</Link><Link className="footer-link" href="/contact">Contact</Link></div></div><div className="border-t border-border px-5 py-6 text-center text-xs text-muted-foreground">© {new Date().getFullYear()} ARSHI GROUP. All rights reserved.</div></footer>
</main>}
