import Link from "next/link";
import { ArrowRight, Bot, Check, ChevronDown, Code2, Globe2, Layers3, Megaphone, MousePointer2, Search, ShieldCheck, ShoppingBag, Sparkles, Target, Workflow, Zap } from "lucide-react";
import ThemeToggle from "@/components/ThemeToggle";
import { Badge } from "@/components/ui/badge";
import { ButtonLink } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

type Service={title:string;text:string;icon:typeof Code2;tag:string};
const services:Service[]=[
 {title:"Web & App Development",text:"Conversion-first websites and web apps engineered for speed, clarity and scale.",icon:Code2,tag:"BUILD"},
 {title:"E-commerce Systems",text:"Shopify, WooCommerce and custom commerce experiences built around buying intent.",icon:ShoppingBag,tag:"COMMERCE"},
 {title:"Performance Marketing",text:"Meta, TikTok, Google, Snapchat and Pinterest campaigns built around measurable growth.",icon:Megaphone,tag:"GROW"},
 {title:"SEO & Growth",text:"Technical SEO, content systems and conversion optimization that compound over time.",icon:Search,tag:"ORGANIC"},
 {title:"AI & Automation",text:"Connected AI workflows and business automation that reduce repetitive work.",icon:Bot,tag:"AUTOMATE"},
 {title:"Brand & Creative",text:"Distinct visual systems, campaigns and creative direction made to earn attention.",icon:Sparkles,tag:"CREATE"},
];
const process=[["01","Discover","Goals, audience, competition and the opportunity in front of you."],["02","Design","Strategy, UX and visual direction shaped around the outcome."],["03","Build","Fast, reliable implementation with clean technical foundations."],["04","Scale","Launch, measure, optimize and turn what works into a system."]];
const faqs=[["What does ARSHI GROUP do?","We combine digital strategy, web development, e-commerce, paid acquisition, SEO, AI automation and creative services under one team."],["Can you improve an existing website or store?","Yes. We can audit, redesign, rebuild, optimize or connect your existing systems without forcing you to start from zero."],["Do you manage TikTok Ads?","Yes. We offer TikTok Ads strategy, setup, campaign management, creative direction and optimization as an independent service provider."],["How does a project start?","Send a project inquiry. We review your goals, current setup and priorities, then recommend the most practical next step."]];
function Heading({eyebrow,title,text}:{eyebrow:string;title:React.ReactNode;text?:string}){return <div className="max-w-3xl"><div className="section-kicker"><span>{eyebrow}</span><i/></div><h2 className="mt-5 text-4xl font-black tracking-[-.04em] sm:text-6xl">{title}</h2>{text&&<p className="mt-5 text-base leading-8 text-muted-foreground sm:text-lg">{text}</p>}</div>}
export default function HomePage(){return <main className="min-h-screen overflow-hidden bg-background text-foreground">
<header className="site-header"><nav className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/" className="brand-mark"><span className="brand-symbol">A</span><span>ARSHI <b>GROUP</b></span></Link><div className="hidden items-center gap-8 md:flex"><Link href="#services" className="nav-link">Services</Link><Link href="#work" className="nav-link">Work</Link><Link href="#process" className="nav-link">Process</Link><Link href="#faq" className="nav-link">FAQ</Link><ThemeToggle/><ButtonLink href="/contact" size="sm">Start a Project <ArrowRight size={15}/></ButtonLink></div><div className="flex items-center gap-2 md:hidden"><ThemeToggle/><details className="relative"><summary className="menu-button">☰</summary><div className="mobile-menu"><Link className="mobile-nav" href="#services">Services</Link><Link className="mobile-nav" href="#work">Work</Link><Link className="mobile-nav" href="#process">Process</Link><Link className="mobile-nav" href="#faq">FAQ</Link><Link className="mobile-nav font-bold text-blue-500" href="/contact">Start a Project →</Link></div></details></div></nav></header>
<section className="hero-shell relative isolate"><div className="hero-noise"/><div className="mx-auto grid min-h-[790px] max-w-7xl items-center gap-16 px-5 py-20 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-24"><div className="hero-copy"><div className="status-pill"><span className="pulse-dot"/> DIGITAL PARTNER <span className="pill-line"/> BUILT FOR GROWTH</div><h1 className="hero-title">Digital work<br/><span>that moves</span><br/>business forward.</h1><p className="hero-lead">ARSHI GROUP builds the digital systems behind ambitious businesses — from high-performance websites and commerce to acquisition, automation and creative.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><ButtonLink href="/contact" size="lg">Start a Project <ArrowRight size={18}/></ButtonLink><ButtonLink href="#services" variant="secondary" size="lg">Explore Services <MousePointer2 size={16}/></ButtonLink></div><div className="hero-proof"><div><strong>01</strong><span>Strategy-led</span></div><div><strong>02</strong><span>Conversion-focused</span></div><div><strong>03</strong><span>Built to scale</span></div></div></div>
<div className="hero-visual"><div className="visual-glow visual-glow-a"/><div className="visual-glow visual-glow-b"/><div className="dashboard-window"><div className="window-bar"><span className="window-dots"><i/><i/><i/></span><span>arshi / growth-os</span><span className="live-tag">LIVE</span></div><div className="window-body"><div className="metric-row"><div><span>Digital momentum</span><strong>+∞</strong></div><div className="metric-spark"><span/><span/><span/><span/><span/><span/><span/></div></div><div className="system-list">{[[Target,"Strategy","Positioning + roadmap"],[Layers3,"Experience","UX + high-performance build"],[Megaphone,"Acquisition","Paid + organic growth"],[Workflow,"Automation","AI + connected workflows"]].map(([Icon,title,desc],i)=>{const I=Icon as typeof Target;return <div className="system-item" key={String(title)}><span className="system-number">0{i+1}</span><span className="system-icon"><I size={18}/></span><span className="system-copy"><b>{String(title)}</b><small>{String(desc)}</small></span><Check size={16} className="system-check"/></div>})}</div><div className="visual-footer"><div><small>NORTH STAR</small><b>Better digital.<br/>Better growth.</b></div><span className="arrow-orbit"><ArrowRight size={20}/></span></div></div></div><div className="floating-card floating-card-top"><Zap size={16}/><span>Systems, not silos.</span></div><div className="floating-card floating-card-bottom"><span className="mini-avatar">AG</span><span><b>One team</b><small>Every digital layer</small></span></div></div></div></section>
<section className="trust-strip"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-x-10 gap-y-5 px-5 py-6 lg:justify-between lg:px-8"><span className="trust-label">CAPABILITIES</span>{services.map(s=><span className="trust-item" key={s.title}><s.icon size={15}/>{s.tag}</span>)}</div></section>
<section id="services" className="section-wrap"><Heading eyebrow="Capabilities" title={<>One team. <span className="soft-gradient">Every digital layer.</span></>} text="Strategy, technology, commerce, performance marketing and automation connected into one growth system — so your digital presence works as one."/><div className="service-grid mt-14">{services.map((s,i)=><Card key={s.title} className="service-card"><div className="service-top"><span className="service-icon"><s.icon size={22}/></span><span className="service-index">0{i+1}</span></div><span className="service-tag">{s.tag}</span><h3>{s.title}</h3><p>{s.text}</p><Link href="/services" className="service-link">Explore capability <ArrowRight size={15}/></Link></Card>)}</div></section>
<section className="feature-section px-5 pb-24 lg:px-8"><div className="feature-panel"><div className="feature-copy"><div className="section-kicker light"><span>Performance marketing</span><i/></div><h2>Make every click<br/><span>work harder.</span></h2><p>Build a performance engine around the platforms your customers already use. Strategy, tracking, creative testing and optimization — connected.</p><div className="feature-points">{["Campaign strategy","Creative testing","Tracking setup","Performance optimization"].map(x=><div key={x}><Check size={16}/>{x}</div>)}</div><ButtonLink href="/services/tiktok-ads" className="mt-8">Explore TikTok Ads <ArrowRight size={16}/></ButtonLink></div><div className="feature-art"><div className="art-ring ring-one"/><div className="art-ring ring-two"/><div className="art-core"><Megaphone size={30}/><span>GROW</span></div><div className="art-label label-a">ATTENTION</div><div className="art-label label-b">ACTION</div><div className="art-label label-c">RETENTION</div></div></div></section>
<section className="section-wrap pt-8"><div className="grid gap-14 lg:grid-cols-[.72fr_1.28fr]"><Heading eyebrow="Why ARSHI" title={<>Not just another <span className="soft-gradient">agency.</span></>} text="We think in systems, not isolated deliverables. Every decision should make the next decision easier, faster and more valuable."/><div className="why-grid">{[[Globe2,"Modern mindset","International standards with practical execution."],[ShieldCheck,"Built with care","Performance, accessibility and security matter."],[Layers3,"Connected thinking","Design, development and growth stay aligned."],[Workflow,"Clear execution","Transparent scope, communication and milestones."]].map(([Icon,title,text])=>{const I=Icon as typeof Globe2;return <Card key={String(title)} className="why-card"><I size={21}/><h3>{String(title)}</h3><p>{String(text)}</p></Card>})}</div></div></section>
<section id="process" className="process-section"><div className="section-wrap"><Heading eyebrow="Process" title={<>Simple process. <span className="soft-gradient">Serious execution.</span></>}/><div className="process-grid mt-14">{process.map(([num,title,text])=><div className="process-step" key={num}><span>{num}</span><div className="process-line"/><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
<section id="work" className="section-wrap"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><Heading eyebrow="Selected work" title={<>Digital experiences<br/><span className="soft-gradient">with purpose.</span></>}/><ButtonLink href="/portfolio" variant="secondary">View portfolio <ArrowRight size={16}/></ButtonLink></div><div className="case-grid mt-14">{[["E-commerce Growth System","COMMERCE"],["High-Performance Brand Platform","WEB"],["TikTok Acquisition Engine","GROWTH"],["AI Operations System","AUTOMATION"]].map(([title,tag],i)=><Card key={title} className="case-card"><div className={`case-art case-art-${i+1}`}><span>{tag}</span><div className="case-art-mark"><Sparkles size={22}/></div><b>0{i+1}</b></div><div className="case-content"><span>CASE STUDY</span><h3>{title}</h3><p>Approved client work and verified results can be added through the portfolio system.</p><Link href="/portfolio" className="service-link">View project <ArrowRight size={15}/></Link></div></Card>)}</div></section>
<section className="testimonial-section"><div className="section-wrap"><div className="testimonial-head"><Heading eyebrow="Client voice" title={<>Trust is built<br/><span className="soft-gradient">project by project.</span></>}/><div className="quote-mark">“</div></div><div className="testimonial-grid">{["A polished placeholder for an approved client testimonial.","A future verified customer quote about strategy and execution.","A future verified customer quote about digital growth."].map((q,i)=><Card key={i} className="testimonial-card"><div className="stars">★★★★★</div><p>“{q}”</p><span>CLIENT NAME · COMPANY</span></Card>)}</div></div></section>
<section id="faq" className="section-wrap"><Heading eyebrow="FAQ" title={<>Questions, answered <span className="soft-gradient">clearly.</span></>}/><div className="faq-list mt-10">{faqs.map(([q,a])=><details key={q} className="faq-item"><summary>{q}<ChevronDown size={19}/></summary><p>{a}</p></details>)}</div></section>
<section className="cta-wrap px-5 pb-24 lg:px-8"><div className="cta-panel"><div className="cta-grid"/><div className="relative z-10"><div className="section-kicker light"><span>Ready when you are</span><i/></div><h2>Let’s build something<br/><span>worth scaling.</span></h2><p>Tell us what you’re building, what’s blocking growth and where you want to go next.</p><ButtonLink href="/contact" variant="secondary" size="lg">Start a Project <ArrowRight size={18}/></ButtonLink></div><div className="cta-orbit"><div>ARSHI</div><span>GROUP</span></div></div></section>
<footer className="site-footer"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:grid-cols-2 lg:grid-cols-[1.7fr_1fr_1fr_1fr] lg:px-8"><div><Link href="/" className="brand-mark"><span className="brand-symbol">A</span><span>ARSHI <b>GROUP</b></span></Link><p className="mt-5 max-w-sm text-sm leading-7 text-muted-foreground">Digital systems, growth and creative execution for ambitious businesses.</p></div><div><p className="footer-title">Explore</p><Link className="footer-link" href="/services">Services</Link><Link className="footer-link" href="/portfolio">Portfolio</Link><Link className="footer-link" href="/services/tiktok-ads">TikTok Ads</Link></div><div><p className="footer-title">Client</p><Link className="footer-link" href="/auth/login">Client login</Link><Link className="footer-link" href="/dashboard">Client portal</Link><Link className="footer-link" href="/contact">Contact</Link></div><div><p className="footer-title">Company</p><Link className="footer-link" href="/privacy">Privacy</Link><Link className="footer-link" href="/terms">Terms</Link><Link className="footer-link" href="/cookies">Cookies</Link></div></div><div className="footer-bottom">© {new Date().getFullYear()} ARSHI GROUP <span>Digital. Designed to grow.</span></div></footer>
</main>}
