import Image from "next/image";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import AdPlaceholder from "@/components/AdPlaceholder";

export default async function BlogPage() {
  const supabase = await createClient();
  const { data: posts } = await supabase.from("blog_posts").select("id,title,slug,excerpt,cover_image_url,published_at,reading_time_minutes").eq("status", "published").or("published_at.is.null,published_at.lte." + new Date().toISOString()).order("published_at", { ascending: false }).limit(30);
  return <main className="section-wrap !py-14 sm:!py-20"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.25em] text-blue-600">ARSHI GROUP · Insights</p><h1 className="mt-4 text-4xl font-black tracking-tight sm:text-6xl">Ideas that help businesses grow.</h1><p className="mt-5 max-w-2xl text-lg text-muted-foreground">Practical insights on websites, e-commerce, performance marketing, SEO, automation and digital growth.</p><AdPlaceholder /><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{(posts ?? []).map((post) => <article key={post.id} className="overflow-hidden rounded-3xl border border-border bg-card transition hover:-translate-y-1 hover:border-blue-500/40"><div className="relative aspect-[16/9] bg-accent">{post.cover_image_url && <Image src={post.cover_image_url} alt={post.title} fill sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw" className="object-cover" />}</div><div className="p-6"><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Insights</p><h2 className="mt-3 text-xl font-black"><Link href={`/blog/${post.slug}`}>{post.title}</Link></h2>{post.excerpt && <p className="mt-3 line-clamp-3 text-sm leading-6 text-muted-foreground">{post.excerpt}</p>}<div className="mt-5 flex items-center justify-between text-xs text-muted-foreground"><span>{post.published_at ? new Date(post.published_at).toLocaleDateString() : "ARSHI GROUP"}</span>{post.reading_time_minutes && <span>{post.reading_time_minutes} min read</span>}</div></div></article>)}{!posts?.length && <div className="rounded-3xl border border-border bg-card p-10 text-muted-foreground md:col-span-2 lg:col-span-3">No published articles yet. Check back soon.</div>}</div></div></main>;
}
